version: 'latest'

services: 
  
  mysql:
    
    image: mysql

    restart: always
    
    environment:
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306
